package com.msk.common.config;

/**
 * ConfigConstantDef
 *
 * @author jiang_nan
 * @version 1.0
 **/
public interface ConfigConstantDef {
    /** 系统环境区分 */
    String SYS_ENV = "sys.env";
    String FTP_IP="ftp.ip";
    String FTP_USER ="ftp.user";
    String FTP_PWD = "ftp.pwd";
    String FTP_IMAGE_ROOT_PATH = "ftp.imageRootPath";
    String WMS_FTP_IP = "wms.ftp.ip";
    String WMS_FTP_USER = "wms.ftp.user";
    String WMS_FTP_PWD = "wms.ftp.pwd";

    String BATCH_PLATE_URL = "batch.plateUrl";
    String BATCH_DISTRIBUTE_URL = "batch.distributeUrl";

    String SMS_SEND_URL = "SMS.SEND.URL";
    String  FILE_SERVER_UPLOAD="file.server.upload";
    String  FILE_SERVER="file.server";
    /**MSK ORG Services */
    String MSK_ORG_SERVICES = "MSK.ORG.SERVICES";
    /**Login Services*/
    String ORG_LOGIN_SERVICES = "ORG.LOGIN.SERVICES";
    /**供应商登录接口*/
    String ORG_LOGIN_SUPP_SERVICES = "ORG.LOGIN.SUPP.SERVICES";
    /**Login Services*/
    String ORG_LOGIN_SUPP_DAO = "ORG.LOGIN.SUPP.SEARCH.SERVICES";
    /**Page List Services*/
    String ORG_PAGE_SERVICES = "ORG.PAGE.SERVICES";
    /**Menu List Services*/
    String ORG_MENU_SERVICES = "ORG.MENU.SERVICES";
    /**卖家可用库存列表*/
    String STOCK_BYSELLER_LIST_SERVICES = "STOCK.BYSELLER.LIST.SERVICES";
    /** 根据pdTypCode查询卖家库存 */
    String STOCK_BYPDTYPECODE_LIST_SERVICES = "STOCK.BYPDTYPECODE.LIST.SERVICES";
    /**snk-price Slpdcode Search Services*/
    String SNK_PRICE_SLPDCODE_SEARCH_SERVICES = "SNK.PRICE.SLPDCODE.SEARCH.SERVICES";
    /** 卖家可用库存列表 */
    String SNK_PRICE_QUERYSTOCKBYSELLER_LIST_SERVICES = "SNK.PRICE.QUERYSTOCKBYSELLER.LIST.SERVICES";

    /**获取下一个价盘周期编码*/
    String SNK_PRICE_PRICECYCLE_SERVICES = "SNK.PRICE.PRICECYCLE.SERVICES";

    /** 查询供应商产品信息 */
    String PRODUCT_GETPDSUPP_SERVICES = "PRODUCT.GETPDSUPP.SERVICES";
    /**msk Stock Services*/
    String MSK_STOCK_SERVICES = "MSK.STOCK.SERVICES";
    /**Msk Snk Price Services*/
    String MSK_SNK_PRICE_SERVICES = "MSK.SNK.PRICE.SERVICES";
    /**Msk Seller Services*/
    String MSK_SELLER_SERVICES = "MSK.SELLER.SERVICES";
    /**Msk Product Services*/
    String MSK_PRODUCT_SERVICES = "MSK.PRODUCT.SERVICES";
    /**Msk Order Services*/
    String MSK_ORDER_SERVICES = "MSK.ORDER.SERVICES";
    /**Msk District Services*/
    String MSK_DISTRICT_SERVICES = "MSK.DISTRICT.SERVICES";
    /**Msk Cash Pooling Services*/
    String MSK_CASH_POOLING_SERVICES = "MSK.CASH.POOLING.SERVICES";
    /**Msk Buyers Services*/
    String MSK_BUYERS_SERVICES = "MSK.BUYERS.SERVICES";
    /**查询物流区信息*/
    String DISTRICT_QUERY_LGCSAREA_SERVICES = "DISTRICT.QUERY.LGCSAREA.SERVICES";
    /**Seller Ep Name Search Services*/
    String SELLER_EPDATA_SEARCH_SERVICES = "SELLER.EPDATA.SEARCH.SERVICES";
    /**查询物流区供应商信息*/
    String SELLER_LGCSSLINFO_SEARCH_SERVICES = "SELLER.LGCSSLINFO.SEARCH.SERVICES";

    /**更新买手店管家专属会员表*/
    String SELLER_SLBSBUYER_UPDATE_SERVICES = "SELLER.SLBSBUYER.UPDATE.SERVICES";


    //查询某区域中所有的买家
    String BUYERS_DISIRICTCODE_ALLBUYERS_SERVICES = "BUYERS.DISIRICTCODE.ALLBUYERS.SERVICES";

    //查询买家所有相关的信息
    String BUYERS_BUYERINFO_RELATIONINFO_SERVICES = "BUYERS.BUYERINFO.RELATIONINFO.SERVICES";

    //查询公共买家池买家信息
    String BUYERS_SEARCH_BUYER_SERVICES = "BUYERS.SEARCH.BUYER.SERVICES";

    //查询买手店管家会员信息
    String BUYERS_SEARCH_BUYER_SHOP_SERVICES = "BUYERS.SEARCH.BUYER.SHOP.SERVICES";

    //查询买手冻品管家的买家信息
    String BUYERS_SEARCH_BUYER_EXCLUSIVE_SERVICES = "BUYERS.SEARCH.BUYER.EXCLUSIVE.SERVICES";

    //供应商可用库存
    String STOCK_BYSUPPLIER_LIST_SERVICES = "STOCK.BYSUPPLIER.LIST.SERVICES";

    //批量查询产品信息
    String PRODUCT_BATCHNAME_SERVICES = "PRODUCT.BATCHNAME.SERVICES";

    //查询档案卡信息
    String PRODUCT_STD_SERVICES = "PRODUCT.STD.SERVICES";

    /**查询产品原料产地接口*/
    String PRODUCT_CLASSTREEMAT_SEARCH_SERVICES = "PRODUCT.CLASSTREEMAT.SEARCH.SERVICES";

    /**查询卖家申请产品审核数据接口*/
    String PRODUCT_PROVIDER_PACKAGE_SEARCH_SERVICES = "PRODUCT.PROVIDER.PACKAGE.SEARCH.SERVICES";

    /**获取产品总控目录数据接口*/
    String PRODUCT_PROVIDER_LIST_SEARCH_SERVICES = "PRODUCT.PROVIDER.LIST.SEARCH.SERVICES";

    /**查询产品标准接口*/
    String PRODUCT_STANDARD_SEARCH_SERVICES = "PRODUCT.STANDARD.SEARCH.SERVICES";

    /**保存产品加工质量标准表接口*/
    String PRODUCT_SAVE_MCT_PROVIDER_SERVICES = "PRODUCT.SAVE.MCT.PROVIDER.SERVICES";

    /**查询产品主码接口*/
    String PRODUCT_ALL_PDCODE_SERVICES = "PRODUCT.ALL.PDCODE.SERVICES";

    /**查询产品一级分类接口*/
    String PRODUCT_CLASSES_SEARCH_SERVICES = "PRODUCT.CLASSES.SEARCH.SERVICES";

    /**查询产品二级分类接口*/
    String PRODUCT_MACHINING_SEARCH_SERVICES = "PRODUCT.MACHINING.SEARCH.SERVICES";

    /**查询产品品种接口*/
    String PRODUCT_BREED_SEARCH_SERVICES = "PRODUCT.BREED.SEARCH.SERVICES";

    /**查询产品特征接口*/
    String PRODUCT_FEATURE_SEARCH_SERVICES = "PRODUCT.FEATURE.SEARCH.SERVICES";

    /**查询产品净重接口*/
    String PRODUCT_WEIGHT_SEARCH_SERVICES = "PRODUCT.WEIGHT.SEARCH.SERVICES";

    /**查询产品包装接口*/
    String PRODUCT_NORMS_SEARCH_SERVICES = "PRODUCT.NORMS.SEARCH.SERVICES";

    //获取价盘区域接口
    String PRODUCT_PRICE_PRD_LOGIAREA_SERVICES = "PRODUCT.PRICE.PRD.LOGIAREA.SERVICES";

    //根据条件插入技术标准信息
    String PRODUCT_SAVE_TNCSTD_DISCUSS_PROVIDER_SERVICES = "PRODUCT.SAVE.TNCSTD.DISCUSS.PROVIDER.SERVICES";

    //根据条件插入申请审核产品信息
    String PRODUCT_SAVE_PROVIDER_PACKAGE_SERVICES = "PRODUCT.SAVE.PROVIDER.PACKAGE.SERVICES";

    //查询卖家产品编码
    String SELLER_SLPDCODE_SEARCH_SERVICES = "SELLER.SLPDCODE.SEARCH.SERVICES";

    //查询供应商名称
    String SELLER_SLEPNAME_SEARCH_SERVICES = "SELLER.SLEPNAME.SEARCH.SERVICES";

    //批量查询卖家身份企业信息
    String SELLER_SLEPDATALIST_SEARCH_SERVICES = "SELLER.SLEPDATALIST.SEARCH.SERVICES";

    //根据查询卖家(显示)编码
    String SELLER_SLSELLERCODE_SEARCH_SERVICES = "SELLER.SLSELLERCODE.SEARCH.SERVICES";

    //查询卖家银行卡信息
    String SELLER_SLBASEINFO_SEARCH_SERVICES = "SELLER.SLBASEINFO.SEARCH.SERVICES";

    //查询买手信息
    String SELLER_SLBSBUYER_SEARCH_SERVICES = "SELLER.SLBSBUYER.SEARCH.SERVICES";

    //查询卖家产品货号信息
    String SELLER_SLPDARTNO_SEARCH_SERVICES = "SELLER.SLPDARTNO.SEARCH.SERVICES";

    //查询卖家产品品牌信息（多个)
    String SELLER_SLPDBRAND_SEARCH_SERVICES = "SELLER.SLPDBRAND.SEARCH.SERVICES";

    //查询冻品管家账户信息
    String SELLER_SLHOUSEACCOUNT_SEARCH_SERVICES = "SELLER.SLHOUSEACCOUNT.SEARCH.SERVICES";

    //查询卖家产品信息
    String SELLER_SLPRODUCT_SEARCH_SERVICES = "SELLER.SLPRODUCT.SEARCH.SERVICES";

    //新增卖家产品状态履历
    String SELLER_SLPDSTATUSHIS_NEW_SERVICES = "SELLER.SLPDSTATUSHIS.NEW.SERVICES";

    //获取生产商,品牌ID
    String SELLER_MANUFACTUREANDBRAND_SEARCH_SERVICES = "SELLER.MANUFACTUREANDBRAND.SEARCH.SERVICES";

    //根据卖家产品查询产品生产商
    String SELLER_SLPROP_SEARCH_SERVICES = "SELLER.SLPROP.SEARCH.SERVICES";

    //查询创建时间范围内的卖家用户
    String SELLER_SOSALESRANKING_SEARCH_SERVICES = "SELLER.SOSALESRANKING.SEARCH.SERVICES";

    //查询卖家名称和编码
    String SELLER_SLCODENAME_SEARCH_SERVICES = "SELLER.SLCODENAME.SEARCH.SERVICES";

    //查询卖家供应商名称和编码
    String SELLER_SLCODESHOWNAME_SEARCH_SERVICES = "SELLER.SLCODESHOWNAME.SEARCH.SERVICES";

    //查询卖家产品分页信息
    String SELLER_SLSELLERPRODUCT_SEARCH_SERVICES = "SELLER.SLSELLERPRODUCT.SEARCH.SERVICES";

    //查询卖家产品目录报表
    String SELLER_SLPROREPORT_SEARCH_SERVICES = "SELLER.SLPROREPORT.SEARCH.SERVICES";

    //查询企业名称和企业ID
    String SELLER_SLENTERPRISE_LIST_SERVICES = "SELLER.SLENTERPRISE.LIST.SERVICES";

    //查询卖家产品编码和名称
    String SELLER_SLPRODUCT_LIST_SERVICES = "SELLER_SLPRODUCT_LIST_SERVICES";


    //更新库存
    String STOCK_OF_SUPPLIER_LIST_SAVE_SERVICES = "STOCK.OF.SUPPLIER.LIST.SAVE.SERVICES";

    //取消供应商冻结库存
    String STOCK_SUPP_CANCEL_FROZEN_SERVICES = "STOCK.SUPP.CANCEL.FROZEN.SERVICES";

    //取消卖家冻结库存
    String STOCK_SL_CANCEL_FROZEN_SERVICES = "STOCK.SL.CANCEL.FROZEN.SERVICES";

    //按条件查询供应商库存
    String STOCK_QTY_QUERY_STOCK_BYSUPPLIER_SERVICES = "STOCK.QTY.QUERY.STOCK.BYSUPPLIER.SERVICES";

    /**查询产品分类接口*/
    String PRODUCT_CLASSTREE_SERVICES = "PRODUCT.CLASSTREE.SERVICES";
    /**查询大区信息*/
    String DISTRICT_QUERY_AREA_SERVICES = "DISTRICT.QUERY.AREA.SERVICES";
    /**查询省信息*/
    String DISTRICT_QUERY_PROVINCE_SERVICES = "DISTRICT.QUERY.PROVINCE.SERVICES";
    /**查询城市信息*/
    String DISTRICT_QUERY_CITY_SERVICES = "DISTRICT.QUERY.CITY.SERVICES";
    /**查询区县信息*/
    String DISTRICT_QUERY_DISTRICT_SERVICES = "DISTRICT.QUERY.DISTRICT.SERVICES";
    /**查询行政规划信息*/
    String DISTRICT_QUERY_REGION_SERVICES = "DISTRICT.QUERY.REGION.SERVICES";
    /**Seller Oneclass Search Services*/
    String SELLER_ONECLASS_SEARCH_SERVICES = "SL.ONECLASS.SEARCH.SERVICES";
    /**查询产品包装*/
    String PRODUCT_PDPACKAGE_SERVICES = "PRODUCT.PDPACKAGE.SERVICES";
    /**根据编号查询名称*/
    String PRODUCT_PDTYPENAME_SERVICES = "PRODUCT.PDTYPENAME.SERVICES";
    /**根据编码查询产品信息（编码可变）*/
    String PRODUCT_PDINFO_SERVICES = "PRODUCT.PDINFO.SERVICES";

    /**根据批量产品编码以及条件查询产品信息*/
    String PRODUCT_PDINFOS_SERVICES = "PRODUCT.PDINFOS.SERVICES";

    /** 记录交易明细 */
    String CP_TRANSACTION_SERVICES = "CP.TRANSACTION.SERVICES";

    /** 记录支付明细 */
    String CP_RUNNING_SERVICES = "CP.RUNNING.SERVICES";

    /** 记录卖家计费项 */
    String CP_SELLERCHARGING_SERVICES = "CP.SELLERCHARGING.SERVICES";


    /**查询订单信息*/
    String ORDER_DETAIL_SERVICES = "ORDER.DETAIL.SERVICES";
    /**供应商上半月销售排名*/
    String ORDER_HALF_MONTH_SERVICES = "ORDER.HALF.MONTH.SERVICES";
    /**文件上传接口*/
    String FILE_UPLOAD_SERVICES= "FILE.UPLOAD.SERVICES";
    /**日志分析接口*/
    String LOG_ANALYSIS_SERVICES = "LOG.ANALYSIS.SERVICES";

    //DS
    /**获取截止本月15日止的已列入供应计划尚未入库的供应量*/
    String DS_UNDONUM_SERVICES = "DS.UNDONUM.SERVICES";
    /**DS模块*/
    String MSK_DS_SERVICES = "MSK.DS.SERVICE";
    /**文件下载接口*/
    String MSK_FILE_DOWNLOAD_SERVICES = "MSK.FILE.DOWNLOAD.SERVICE";

    /** SSO站点外网地址 */
    String SSO_URL_OUTSIDE = "sso.url.outside";
    /** SSO站点内网地址 */
    String SSO_URL_INSIDE = "sso.url.inside";

    /** Web站点地址 */
    String WEB_SERVER = "web.server.url";
    /** 内部API调用根地址 */
    String API_SERVER = "api.url.inside";


}
